### ISSUE TITLE
Remove SUID/SGID bits automatically (with excludes)

### ISSUE THREAD

**Issue by ok-ryoko** [ok-ryoko/turret#5]
### Code of conduct

- [X] I have read and agree to the community’s code of conduct.

### Use case(s)

To remove all SUID/SGID (`s`) bits on files in the working container, I have to list all the special files in my spec. For every base image, I therefore have to jump into a container and identify those files myself.

### Ideal solution

We should be able to specify that we want the program to automatically look for and remove all `s` bits it finds except for those files that we name explicitly:

```toml
[security.special-files]
remove-s = true
excludes = [ "/usr/bin/mount" ]
```

`remove-s` would default to `false`, so `excludes` would be ignored unless we set `remove-s` to `true`.
